apiVersion: v1
kind: Pod
metadata:
  labels:
    app: arkcase
  name: arkcase
spec:
  containers:
  - env:
    image: 345280441424.dkr.ecr.ap-south-1.amazonaws.com/ark_arkcase_core:latest
    imagePullPolicy: Always
    #command: ["/bin/sleep", "180d"]
    name: arkcase
    ports:
    - containerPort: 8080
      name: console
      protocol: TCP
  hostname: arkcase
  imagePullSecrets:
  - name: aws-arkcase-pull
