name: Build and Deploy to ECR
on:
  push:
    branches: [ develop ]
jobs:
  build-and-push-ecr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1
        environment: development
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: download artifacts
        run: ./getArtifact.sh
      - name: login to ECR repo
        uses: aws-actions/amazon-ecr-login@v1
        id: login-ecr
      - name: build and publish to ecr
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: arkcase_core
          IMAGE_TAG: test
        run: |
          docker build -t  $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          