name: Build and Deploy to ECR
on:
  push:
    branches: [ "develop" ]
jobs:
  build-and-push-ecr:
    runs-on: ubuntu-latest
    environment: development
    env:
      ARKCASE_VERSION: 2021.03-RC11
    steps:
      - uses: actions/checkout@v2
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: download artifacts
        run: ./getArtifact.sh
      - name: login to ECR repo
        uses: aws-actions/amazon-ecr-login@v1
        id: login-ecr
      - name: build and publish to ecr
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: arkcase_core
          TOMCAT_VERSION: 9.0.50 
          TOMCAT_MAJOR_VERSION: 9
          SYMMETRIC_KEY: 99999999
          MARIADB_CONNECTOR_VERSION: 2.2.5
          RESOURCE_PATH: artifacts
        run: |
          docker build -t  $ECR_REGISTRY/$ECR_REPOSITORY:$ARKCASE_VERSION --build-arg TOMCAT_VERSION --build-arg ARKCASE_VERSION --build-arg TOMCAT_MAJOR_VERSION --build-arg  SYMMETRIC_KEY --build-arg MARIADB_CONNECTOR_VERSION --build-arg RESOURCE_PATH .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$ARKCASE_VERSION
          
